# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty


# Setup
title:            MARlab
description:      'Methodology & Analysis Research Lab'
url:              http://marlab.com
baseurl:          /

author:
  name:           'Alex Schoemann'
  url:            https://sites.google.com/site/alexandermschoemann/

paginate:         5

# Custom vars
version:          2.1.0


