# Dependencies
highlighter:      rouge 

# Permalinks
permalink:        pretty


# Setup
title:            MARlab
description:      'Methodology & Analysis Research Lab'
url:              http://marlab.com
baseurl:          /

author:
  name:           'Alex Schoemann'
  url:            https://sites.google.com/site/alexandermschoemann/

paginate:         5

# Google services
google_analytics: UA—68910433-1

# Custom vars
version:          2.1.0

#Markdown processor
markdown: redcarpet

