# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            MARlab
tagline:          ''
description:      'Methodology & Analysis Research Lab at ECU'
url:              http://marlab.com
baseurl:          /

author:
  name:           'Alex Schoemann'
  url:            https://sites.google.com/site/alexandermschoemann/

paginate:         5

# Custom vars
version:          2.1.0


